{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-inventory
  namespace: {{ .Values.namespace }}
  labels:
    subnet.node: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-service
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.serviceAccount.hardwareDiscovery.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-inventory-hardware-discovery
  namespace: {{ .Values.namespace }}
  labels:
    subnet.node: "true"
    app.kubernetes.io/name: inventory
    app.kubernetes.io/instance: inventory-hardware-discovery
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: provider
  {{- with .Values.serviceAccount.hardwareDiscovery.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

